### ISSUE TITLE
hyperparameter of Table2

### ISSUE THREAD

**Issue by JingyangXiang** [MingSun-Tse/TPP#2]
Thank you very much for your excellent work！I want to reproduce the results of Tab2. Could you please share your hyperparameters?
Thank you very much!

**Comment by MingSun-Tse** [comment]
Hi @JingyangXiang thanks for your interest! The scripts to reproduce are already in README: https://github.com/MingSun-Tse/TPP#tab-2-resnets-on-imagenet

Please just follow the README exactly. Let me know if you have further questions!
