### ISSUE TITLE
the mean and var of cifar 10

### ISSUE THREAD

**Issue by ZS-YANG** [MingSun-Tse/TPP#3]
哈喽 作者大大。有个问题想请教下，网上查询到cifar10数据集的均值和方差为(0.4914, 0.4822, 0.4465)和(0.2023, 0.1994, 0.2010)，是出于什么原因，在本文中(https://github.com/MingSun-Tse/TPP/blob/master/data/cifar10.py )使用的均值和方差变为MEAN = (0.485, 0.456, 0.406)和STD  = (0.229, 0.224, 0.225)呢😖😖

**Comment by MingSun-Tse** [comment]
你好! 这个如code中注释，使用的是imagenet的mean和std。没有特别的原因，好像是很早之前发现imagenet的mean std得到的结果略高一点。换回原来的mean std估计没什么大的变化。

**Comment by ZS-YANG** [comment]
> 你好! 这个如code中注释，使用的是imagenet的mean和std。没有特别的原因，好像是很早之前发现imagenet的mean std得到的结果略高一点。换回原来的mean std估计没什么大的变化。

好嘞，感谢大佬回复
